#! /bin/sh
# Set Keyboard layout
    setxkbmap br &

#Auto config display
    autorandr auto &
    #bspc monitor -g 2559x1080+0+0 &
    #bspc monitor -g 1366x768+0+0

#Set workspaces
    bspc monitor -d I II III IV V

#Launch polybar
    bash ~/.config/polybar/launch.sh --blocks &

#Launch Picom 
    picom --experimental-backends &

#Fix cursor
    xsetroot -cursor_name left_ptr &

#Fix some other stuff
    pgrep -x sxhkd > /dev/null || sxhkd &

#Grab pywal palette
    . "${HOME}/.cache/wal/colors.sh"




bspc config border_width		 5
bspc config window_gap          	 50
bspc config top_padding			 0
bspc config bottom_padding       -20
bspc config split_ratio         	 0.5
bspc config borderless_monocle  	 true
bspc config gapless_monocle      	 true
bspc config normal_border_color 	 "$color1"
bspc config focused_border_color	 "$color4"
bspc config focus_follows_pointer	 true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Emacs state=tiled
